### ISSUE TITLE
Odyssey Jb ios 13.6.1 black screen

### ISSUE THREAD

**Issue by hellisabove** [Odyssey-Team/Odyssey#43] opened 2020-12-15 14:12 UTC
Hi, I just jailbroke my iPhone 7 on ios 13.6.1 and if I leave my phone a little and then want to go to home screen I can't because my screen is black and the single thing that fixes it is restarting my phone and even if I rejailbreak it the issue comes again

Edit: After a little while it unjailbreaks and I have to jailbreak it again.
Edit 2: Got in Cr4shed a log for siriactionsd with unknown culprit

**Comment by vickvick3110** [comment] 2020-12-15 15:06
i got this too, on iPhone 7 Plus 13.6

**Comment by imtaiger** [comment] 2020-12-18 22:14
I have this problem too 13.6.1 iphone 7

**Comment by ugcgt** [comment] 2021-01-08 10:27
- [ ]

**Comment by MOHAMMED-511** [comment] 2021-01-17 07:36
Hi

**Comment by coupedeebaybee** [comment] 2021-02-20 07:02
I have the same issue. Very annoying. 
I’ve restoreRootFS’d my device at least 5 times & it seems to only happen after libhooker has been installed. 
The last few times I’ve really tried to narrow down the culprit, as it is seemingly random, & only installed appsync, which has libhooker as a dependency. 
I haven’t personally confirmed this as 100% yet or done much logging, but I’ve only had this phone for about a week. 
But it seems to only happen after I’ve installed libhooker.
This is a very annoying bug. 
Disappointed to see zero response from the devs as of yet. Why do we even have ‘issues’ on buggy code if the devs won’t even acknowledge their existence.

iPhone 7, 13.6

**Comment by chrismonster13** [comment] 2021-02-20 08:11
I normally like to chime in because I've been using Odyssey/Odysseyra1n since they came out with zero issues. I have 188 dylibs running on my device at all times. What tweaks do you use?

**Comment by hellisabove** [comment] 2021-02-20 15:45
> I normally like to chime in because I've been using Odyssey/Odysseyra1n since they came out with zero issues. I have 188 dylibs running on my device at all times. What tweaks do you use?

None. I jailbreak, update, install libhooker and then after a few minutes it doesn't have the jailbreak anymore.

**Comment by chrismonster13** [comment] 2021-02-20 16:14
> > I normally like to chime in because I've been using Odyssey/Odysseyra1n since they came out with zero issues. I have 188 dylibs running on my device at all times. What tweaks do you use?
> 
> 
> 
> None. I jailbreak, update, install libhooker and then after a few minutes it doesn't have the jailbreak anymore.

hmmmm. are you installing the correct version of AppSync?

**Comment by coupedeebaybee** [comment] 2021-02-22 06:36
My people, i have stumbled across a fix for this issue. Install NewTerm, & as root run this command “rm /.disable_tweakinject && killall backboardd”
Then run “ldrestart”. Then run “killall SpringBoard“.

It got so bad for me that even upon initial jailbreak, with only essential packages installed, it would have this black screen/kernel panic reboot issue upon locking. Stumbled across a post on twitter that had a reply that said to run those commands & I happily announce that it has seemingly fixed this issue for me!

**Comment by coupedeebaybee** [comment] 2021-02-22 21:32
> 
> 
> My people, i have stumbled across a fix for this issue. Install NewTerm, & as root run this command “rm /.disable_tweakinject && killall backboardd”
> Then run “ldrestart”. Then run “killall SpringBoard“.
> 
> It got so bad for me that even upon initial jailbreak, with only essential packages installed, it would have this black screen/kernel panic reboot issue upon locking. Stumbled across a post on twitter that had a reply that said to run those commands & I happily announce that it has seemingly fixed this issue for me!

**That's a big NEVERMIND. The issue went away for a while, I left the device alone, after having nothing but essential packages installed, it still had rebooted itself when I came back to it later**

**Comment by grittyridez** [comment] 2021-03-03 23:02
I HAVE THIS ISSUE ON 13.5.1 PLEASE TELL ME IF YOU FIND A FIX

**Closed** 2022-02-21 18:44 UTC
